### ISSUE TITLE
Black pillbox still present

### ISSUE THREAD

**Issue by LGarry564** [Lyall/DeadIsland2Fix#5]
Hi there Lyall, 

I'ved done as per instruction to paste into the Dead Island 2 game files but once i launched it the black box still appeared both gameplay and cutscenes .. any thoughts to fix it? 

My platform: Epic Games bought at preorder stage 
my monitor: 2560x1080

**Comment by LGarry564** [comment]
> Hi there Lyall,
> 
> I'ved done as per instruction to paste into the Dead Island 2 game files but once i launched it the black box still appeared both gameplay and cutscenes .. any thoughts to fix it?
> 
> My platform: Epic Games bought at preorder stage my monitor: 2560x1080

![Untitled](https://github.com/Lyall/DeadIsland2Fix/assets/160830956/c1733f04-1af9-4c70-8de6-e29f6bfce444)

**Comment by LGarry564** [comment]
> > Hi there Lyall,
> > I'ved done as per instruction to paste into the Dead Island 2 game files but once i launched it the black box still appeared both gameplay and cutscenes .. any thoughts to fix it?
> > My platform: Epic Games bought at preorder stage my monitor: 2560x1080
> 
> ![Untitled](https://private-user-images.githubusercontent.com/160830956/306909070-c1733f04-1af9-4c70-8de6-e29f6bfce444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1ODg3MTIsIm5iZiI6MTcwODU4ODQxMiwicGF0aCI6Ii8xNjA4MzA5NTYvMzA2OTA5MDcwLWMxNzMzZjA0LTFhZjktNGM3MC04ZGU2LWUyOWY2YmZjZTQ0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwNzUzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTQ1MTIwOTFlMDViOGY3ZTQ0NDNlNzVmNDU4YjUwY2MxN2JkMmVlYmJhMjBlMzE4ZTIzOTM1ZTQ2NGE4MWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ozp7ypp1mvzrTH1HsRuVlkb7hU7e9Ge5gFOVJzovP2A)

An update, the gameplay it works fine widescreen, only the cutscenes tho .. 
![Untitled](https://github.com/Lyall/DeadIsland2Fix/assets/160830956/e9c7f3f0-bffc-44f5-8f77-81b639ba1f68)

**Comment by Lyall** [comment]
Should be fixed in [v1.0.3.](https://github.com/Lyall/DeadIsland2Fix/releases)
