### ISSUE TITLE
mod need update

### ISSUE THREAD

**Issue by Gitaroo326** [Lyall/DeadIsland2Fix#6]
Hi, mod seems to have stopped working with steam release and latest version on EGS. Getting black bars in real time cut scenes,

**Comment by Lyall** [comment]
Working on it just now. I just need to verify that it actually works with the Steam build.

**Comment by Lyall** [comment]
This should be working now in [v1.0.3](https://github.com/Lyall/DeadIsland2Fix/releases). Let me know if you run in to any problems.
